// <auto-generated />
using System;
using HIOF.GamingSocial.ProfileInformation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HIOF.GamingSocial.ProfileInformation.Data.Migrations
{
    [DbContext(typeof(ProfileInformationDbContext))]
    [Migration("20230525131248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HIOF.GamingSocial.ProfileInformation.Data.Friend", b =>
                {
                    b.Property<Guid>("ProfileGuid1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileGuid2")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProfileGuid1", "ProfileGuid2");

                    b.ToTable("Friend");

                    b.HasData(
                        new
                        {
                            ProfileGuid1 = new Guid("5b98dd2e-33e9-49d0-8e6a-3c5a286a761c"),
                            ProfileGuid2 = new Guid("cdd891fc-5bcc-491e-9aab-0c3d40bee349")
                        },
                        new
                        {
                            ProfileGuid1 = new Guid("d455ce99-45a4-4ee2-932f-5696a5c3b169"),
                            ProfileGuid2 = new Guid("58ed69d7-031d-4c8d-a636-3459afa19b46")
                        },
                        new
                        {
                            ProfileGuid1 = new Guid("5f3a7799-5550-4151-a478-d45fbea29a8a"),
                            ProfileGuid2 = new Guid("5b98dd2e-33e9-49d0-8e6a-3c5a286a761c")
                        },
                        new
                        {
                            ProfileGuid1 = new Guid("cdd891fc-5bcc-491e-9aab-0c3d40bee349"),
                            ProfileGuid2 = new Guid("d455ce99-45a4-4ee2-932f-5696a5c3b169")
                        });
                });

            modelBuilder.Entity("HIOF.GamingSocial.ProfileInformation.Data.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("GroupId");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Description = "A group for DotA 2 enthusiasts to discuss strategies and plan matches.",
                            GroupName = "DotA Heroes",
                            IsHidden = false,
                            IsPrivate = false
                        },
                        new
                        {
                            GroupId = 2,
                            Description = "Join us in mastering the latest FPS games like Valorant, CS:GO, and more.",
                            GroupName = "FPS Masters",
                            IsHidden = false,
                            IsPrivate = false
                        },
                        new
                        {
                            GroupId = 3,
                            Description = "A place for Starcraft players to share insights and game tactics.",
                            GroupName = "Strategic Minds",
                            IsHidden = false,
                            IsPrivate = false
                        });
                });

            modelBuilder.Entity("HIOF.GamingSocial.ProfileInformation.Data.GroupMembership", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId", "ProfileGuid");

                    b.ToTable("GroupMembership");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            ProfileGuid = new Guid("5b98dd2e-33e9-49d0-8e6a-3c5a286a761c"),
                            MemberType = "Owner"
                        },
                        new
                        {
                            GroupId = 2,
                            ProfileGuid = new Guid("cdd891fc-5bcc-491e-9aab-0c3d40bee349"),
                            MemberType = "Owner"
                        },
                        new
                        {
                            GroupId = 3,
                            ProfileGuid = new Guid("d455ce99-45a4-4ee2-932f-5696a5c3b169"),
                            MemberType = "Owner"
                        },
                        new
                        {
                            GroupId = 1,
                            ProfileGuid = new Guid("58ed69d7-031d-4c8d-a636-3459afa19b46"),
                            MemberType = "Member"
                        },
                        new
                        {
                            GroupId = 2,
                            ProfileGuid = new Guid("5f3a7799-5550-4151-a478-d45fbea29a8a"),
                            MemberType = "Member"
                        });
                });

            modelBuilder.Entity("HIOF.GamingSocial.ProfileInformation.Data.Invite", b =>
                {
                    b.Property<int>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InviteId"));

                    b.Property<string>("InviteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ReceiverGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int");

                    b.Property<Guid>("SenderGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InviteId");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("HIOF.GamingSocial.ProfileInformation.Data.Profile", b =>
                {
                    b.Property<Guid>("ProfileGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("nvarchar(56)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProfileGuid");

                    b.ToTable("Profile");

                    b.HasData(
                        new
                        {
                            ProfileGuid = new Guid("5b98dd2e-33e9-49d0-8e6a-3c5a286a761c"),
                            Age = 27,
                            Bio = "DotA 2 enthusiast. Always ready for the next match. Let's climb the ranks together!",
                            Country = "United Kingdom",
                            Name = "Daniel",
                            UserName = "GGDragon"
                        },
                        new
                        {
                            ProfileGuid = new Guid("cdd891fc-5bcc-491e-9aab-0c3d40bee349"),
                            Age = 30,
                            Bio = "FPS addict. Currently mastering CSGO. Join me if you can keep up!",
                            Country = "Germany",
                            Name = "Laura",
                            UserName = "RogueHunter"
                        },
                        new
                        {
                            ProfileGuid = new Guid("d455ce99-45a4-4ee2-932f-5696a5c3b169"),
                            Age = 32,
                            Bio = "Chess player turned Warhammer expert. Looking for strategic minds.",
                            Country = "United States",
                            Name = "Samuel",
                            UserName = "StrategistKing"
                        },
                        new
                        {
                            ProfileGuid = new Guid("58ed69d7-031d-4c8d-a636-3459afa19b46"),
                            Age = 26,
                            Bio = "Retro gaming nerd. From DOOM to Plants vs zombies, I play them all. Let's go back to the classics!",
                            Country = "Japan",
                            Name = "Mia",
                            UserName = "RetroGamer"
                        },
                        new
                        {
                            ProfileGuid = new Guid("5f3a7799-5550-4151-a478-d45fbea29a8a"),
                            Age = 29,
                            Bio = "RPG lover. Exploring the vast world of Elder Scrolls Online. Join my guild and let's quest together!",
                            Country = "Australia",
                            Name = "Dylan",
                            UserName = "EpicQuester"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
